In [3]:
from google.colab import files

In [4]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [39]:
import joblib

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [11]:
from sklearn.model_selection import train_test_split

In [23]:
import sklearn.metrics as sm

In [7]:
import pandas as pd

In [29]:
import numpy as np

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.6, random_state = 0)

In [87]:
from sklearn.tree import DecisionTreeRegressor


In [100]:
data = pd.read_csv("/content/drive/MyDrive/datadeneme33.csv")
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
print(X)

[[1.00e+00 3.00e+00 2.00e+00 ... 1.00e+00 1.00e+00 9.20e+02]
 [1.00e+00 4.00e+00 2.00e+00 ... 1.00e+00 1.00e+00 1.53e+03]
 [1.00e+00 2.00e+00 1.00e+00 ... 2.00e+00 1.00e+00 7.48e+02]
 ...
 [1.00e+00 7.00e+00 3.00e+00 ... 6.02e+02 3.00e+00 2.98e+03]
 [1.00e+00 3.00e+00 1.00e+00 ... 5.99e+02 3.00e+00 1.19e+03]
 [1.00e+00 2.00e+00 2.00e+00 ... 6.04e+02 3.00e+00 1.02e+03]]


In [106]:
print('\nMAE train decision tree reg:            ',mae_train_decision_tree_reg
    ,'\nMAE test decision tree reg:             ',mae_test_decision_tree_reg)


MAE train decision tree reg:             783.8280399922055 
MAE test decision tree reg:              3638.6893513486075


In [105]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [104]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[225000. 225000.]
 [675000. 675000.]
 [585000. 585000.]
 ...
 [ 70000.  70000.]
 [629000. 629000.]
 [459900. 459900.]]


In [103]:
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_pred), 2))
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_pred), 2))
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_pred), 2))
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2))

Mean absolute error = 3663.42
Mean squared error = 838976923.14
Median absolute error = 0.0
Explain variance score = 0.99


In [108]:
regressor.predict([[1,4,3,2.39,1,1,3353]])

array([225000.])

In [109]:
joblib.dump(regressor, 'decision_tree_regression_model.joblib')

['decision_tree_regression_model.joblib']

In [110]:
files.download('decision_tree_regression_model.joblib')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>